export interface BastionRule {
  id: string
  name: string
  description: string
  type: "regex" | "command_prefix" | "contains" | "exact"
  pattern: string
  tool_scope: string[]
  severity: "critical" | "high" | "medium"
  enforcement: "KILL" | "USER_INPUT" | "LLM_EXAMINE" | "INVOKE_ACTION"
  enabled: boolean
  tags: string[]
  suggested_alternative?: string
}

export const RULES: BastionRule[] = [
  {
    id: "R001",
    name: "block_env_access",
    description: "Prevent reading secret/configuration files",
    type: "regex",
    pattern:
      "\\.(env|credentials|secret|pem)($|\\s)|id_rsa|\\.ssh[\\/]|aws[\\/]credentials|\\.gcloud[\\/]|service.account.*\\.json",
    tool_scope: ["bash", "read"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["secrets"],
  },
  {
    id: "R002",
    name: "block_recursive_delete",
    description: "Prevent recursive deletion (rm -rf, rm -r)",
    type: "regex",
    pattern: "rm\\s+(-[rRf]+\\s+)|rm\\s+-[rRf]+|rm\\s+-r\\s+-f",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["destructive"],
  },
  {
    id: "R017",
    name: "block_rm_command",
    description: "Prevent file deletion via rm command",
    type: "command_prefix",
    pattern: "rm ",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["destructive"],
  },
  {
    id: "R016",
    name: "block_apply_patch_delete",
    description: "Prevent file/folder deletion via apply_patch tool",
    type: "regex",
    pattern: "\\*\\*\\*\\s+Delete\\s+File:|delete\\s+file:",
    tool_scope: ["apply_patch"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["destructive"],
  },
  {
    id: "R003",
    name: "block_disk_format",
    description: "Prevent disk formatting and low-level disk operations",
    type: "regex",
    pattern: "\\b(mkfs|fdisk|dd\\s+if=|diskutil\\s+erase|format\\s+[A-Z]:)\\b",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["destructive"],
  },
  {
    id: "R004",
    name: "block_privilege_escalation",
    description: "Prevent privilege escalation commands",
    type: "regex",
    pattern: "\\b(sudo\\s|chmod\\s+777|chown\\s+root|visudo|passwd\\s|su\\s+-|doas\\s)\\b",
    tool_scope: ["bash"],
    severity: "high",
    enforcement: "USER_INPUT",
    enabled: true,
    tags: ["privilege_escalation"],
  },
  {
    id: "R005",
    name: "block_network_exfiltration",
    description: "Prevent data exfiltration via network tools",
    type: "regex",
    pattern: "\\b(curl|wget|nc|netcat|ncat)\\b.*(-d|--data|--upload|--post|-X\\s*POST|>)",
    tool_scope: ["bash"],
    severity: "high",
    enforcement: "LLM_EXAMINE",
    enabled: true,
    tags: ["exfiltration"],
  },
  {
    id: "R006",
    name: "block_reverse_shell",
    description: "Prevent reverse shell patterns",
    type: "regex",
    pattern: "\\b(bash\\s+-i|/dev/tcp/|mkfifo|ncat\\s+-e|nc\\s+-e|python.*socket.*connect|perl.*socket)\\b",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["exfiltration", "reverse_shell"],
  },
  {
    id: "R007",
    name: "block_pipe_to_shell",
    description: "Prevent piping remote content to shell execution",
    type: "regex",
    pattern: "(curl|wget).*\\|\\s*(bash|sh|zsh|python|perl|ruby)",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "INVOKE_ACTION",
    enabled: true,
    tags: ["code_execution"],
  },
  {
    id: "R008",
    name: "block_path_traversal",
    description: "Prevent directory traversal attacks",
    type: "regex",
    pattern: "\\.\\.\\/|\\.\\.\\.\\\\",
    tool_scope: ["read", "write", "edit", "bash"],
    severity: "high",
    enforcement: "KILL",
    enabled: true,
    tags: ["path_traversal"],
  },
  {
    id: "R009",
    name: "block_process_kill",
    description: "Prevent killing system processes",
    type: "regex",
    pattern: "\\b(kill\\s+-9|killall|pkill)\\b",
    tool_scope: ["bash"],
    severity: "medium",
    enforcement: "USER_INPUT",
    enabled: true,
    tags: ["system_modification"],
  },
  {
    id: "R010",
    name: "block_system_modification",
    description: "Prevent modifying system configuration files",
    type: "regex",
    pattern: "\\b(systemctl|service\\s+|crontab|at\\s+|sysctl)\\b",
    tool_scope: ["bash"],
    severity: "high",
    enforcement: "USER_INPUT",
    enabled: true,
    tags: ["system_modification"],
  },
  {
    id: "R011",
    name: "block_git_force_push",
    description: "Prevent force-pushing to git repositories",
    type: "regex",
    pattern: "git\\s+push.*--force|git\\s+push.*-f\\b",
    tool_scope: ["bash"],
    severity: "high",
    enforcement: "USER_INPUT",
    enabled: true,
    tags: ["destructive", "git"],
  },
  {
    id: "R012",
    name: "block_npm_global_install",
    description: "Prevent global npm package installations",
    type: "regex",
    pattern: "npm\\s+install.*-g\\b|npm\\s+i\\s.*-g\\b",
    tool_scope: ["bash"],
    severity: "medium",
    enforcement: "INVOKE_ACTION",
    enabled: true,
    tags: ["system_modification"],
  },
  {
    id: "R013",
    name: "block_base64_exfil",
    description: "Detect base64 encoding piped to network tools (data exfiltration pattern)",
    type: "regex",
    pattern: "base64.*\\|.*(curl|wget|nc)|cat.*\\|.*base64.*\\|.*(curl|wget)",
    tool_scope: ["bash"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["exfiltration"],
  },
  {
    id: "R014",
    name: "block_env_variable_dump",
    description: "Prevent dumping environment variables (may contain secrets)",
    type: "regex",
    pattern:
      "\\b(printenv|env\\b|set\\b)\\s*$|\\bexport\\s+-p\\b|echo\\s+\\$\\{?[A-Z_]*(KEY|SECRET|TOKEN|PASSWORD|CREDENTIAL)",
    tool_scope: ["bash"],
    severity: "high",
    enforcement: "LLM_EXAMINE",
    enabled: true,
    tags: ["secrets", "exfiltration"],
  },
  {
    id: "R015",
    name: "block_write_to_sensitive",
    description: "Prevent writing to sensitive file paths",
    type: "regex",
    pattern: "\\.(env|credentials|secret|pem|key)$|id_rsa|\\.ssh[\\/]|authorized_keys",
    tool_scope: ["write", "edit"],
    severity: "critical",
    enforcement: "KILL",
    enabled: true,
    tags: ["secrets", "system_modification"],
  },
]
